### ISSUE TITLE
The code generates a trailing comma in the Update clause

### ISSUE THREAD

**Issue by terenceholland** [dnlnln/generate-sql-merge#58] opened 2019-04-24 13:32 UTC
The code generates a trailing comma in the Update clause.

**Comment by dnlnln** [comment] 2019-04-25 00:59
I cannot reproduce this. Are you able to provide repro steps?

**Comment by terenceholland** [comment] 2019-04-25 08:25
I installed the script on this version...

Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 17134: ) (Hypervisor)  

Then simply ran
exec sp_generate_merge @table_name='MyTable'

**Comment by dnlnln** [comment] 2019-04-25 08:48
I have a very similar spec instance here (SQL 14.0.2002.14) and unfortunately am unable to reproduce. Are you able to script a create statement for `MyTable` and post it here? If not, does it happen if you run it against the MS sample db? e.g.
```
EXEC [AdventureWorks2017].dbo.sp_generate_merge 'AddressType', @schema = 'Person'
```

**Comment by terenceholland** [comment] 2019-04-25 09:47
I dont have AdventureWorks installed.

Im running script agains this table

CREATE TABLE [dbo].[Plugin](
[Id] [int] IDENTITY(1,1) NOT NULL,
[PluginGuid] [uniqueidentifier] NOT NULL,
[Name] [varchar](50) NOT NULL,
[Description] [varchar](max) NOT NULL,
[MaxDegreeOfParallelism] [int] NOT NULL,
[Active] [bit] NOT NULL,
 CONSTRAINT [PK_Plugin] PRIMARY KEY CLUSTERED 
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Plugin] ADD  CONSTRAINT [DF_Plugin_MaxDegreeOfParallelism]  DEFAULT ((0)) FOR [MaxDegreeOfParallelism]
GO


The generated script is...
--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [plugin] ON

MERGE INTO [plugin] AS [Target]
USING (VALUES
  (34,N'0B25578A-06B2-43CC-B7DB-B0B6CF4D2005',N'Test-Plugin-Example',N'First Plugin in the Test Db',2,0)
 ,(35,N'AA3E6541-1EC0-4611-9698-8D590151765D',N'Test-Plugin-Example',N'First Plugin in the Test Db',2,0)
 
 --deleted 1000+ rows for brevity
 
 
) AS [Source] ([Id],[PluginGuid],[Name],[Description],[MaxDegreeOfParallelism],[Active])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
NULLIF([Source].[PluginGuid], [Target].[PluginGuid]) IS NOT NULL OR NULLIF([Target].[PluginGuid], [Source].[PluginGuid]) IS NOT NULL OR 
NULLIF([Source].[Name], [Target].[Name]) IS NOT NULL OR NULLIF([Target].[Name], [Source].[Name]) IS NOT NULL OR 
NULLIF([Source].[Description], [Target].[Description]) IS NOT NULL OR NULLIF([Target].[Description], [Source].[Description]) IS NOT NULL OR 
NULLIF([Source].[MaxDegreeOfParallelism], [Target].[MaxDegreeOfParallelism]) IS NOT NULL OR NULLIF([Target].[MaxDegreeOfParallelism], [Source].[MaxDegreeOfParallelism]) IS NOT NULL OR 
NULLIF([Source].[Active], [Target].[Active]) IS NOT NULL OR NULLIF([Target].[Active], [Source].[Active]) IS NOT NULL) THEN
 UPDATE SET
  [PluginGuid] = [Source].[PluginGuid],

  [Name] = [Source].[Name],

  [Description] = [Source].[Description],

  [MaxDegreeOfParallelism] = [Source].[MaxDegreeOfParallelism],

  [Active] = [Source].[Active],
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[PluginGuid],[Name],[Description],[MaxDegreeOfParallelism],[Active])
 VALUES([Source].[Id],[Source].[PluginGuid],[Source].[Name],[Source].[Description],[Source].[MaxDegreeOfParallelism],[Source].[Active])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE
;
GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [plugin]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[plugin] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET IDENTITY_INSERT [plugin] OFF
GO
SET NOCOUNT OFF
GO

**Comment by terenceholland** [comment] 2019-04-25 11:11
You will also notice that in my example, there is double line spacing on the UPDATE clause section

**Comment by dnlnln** [comment] 2019-04-26 01:15
Thanks for providing that extra detail, that helped a lot.

I think the issue may have stemmed from the way that new lines are appended for each column in the update list. I've prepared a fix (#59), would you mind installing this version and seeing if it fixes the issue for you? https://github.com/readyroll/generate-sql-merge/blob/cff3542c824692db37aeb602e585980ac1d7f5ea/master.dbo.sp_generate_merge.sql

**Comment by terenceholland** [comment] 2019-04-26 16:10
This now works

**Comment by dnlnln** [comment] 2019-04-27 04:30
Thanks, now merged

**Closed as completed** 2019-04-27 04:29 UTC
