### ISSUE TITLE
instruction(x)' contains an invalid XML identifier as required by FOR XML

### ISSUE THREAD

**Issue by spottedmahn** [dnlnln/generate-sql-merge#96] opened 2023-08-13 22:51 UTC
[the 8/7/23 file](https://github.com/dnlnln/generate-sql-merge/blob/16f28006ef42f5121b88763b5c342886e8b41fbf/master.dbo.sp_generate_merge.sql) is erroring ❌ on install for me:

>Using Master database
Checking for the existence of this procedure
Procedure already exists. So, dropping it
Msg 6850, Level 16, State 1, Procedure sp_generate_merge, Line 964 [Batch Start Line 14]
Column name 'processing - instruction(x)' contains an invalid XML identifier as required by FOR XML; ' '(0x0020) is the first character at fault.
Created the procedure
sp_MS_marksystemobject: Invalid object name 'sp_generate_merge'
Granting EXECUTE permission on sp_generate_merge to all users
Msg 15151, Level 16, State 1, Line 1005
Cannot find the object 'sp_generate_merge', because it does not exist or you do not have permission.
Done
Completion time: 2023-08-13T18:46:04.3948666-04:00

---

I was able to successfully install [this version from 7/31/23](https://github.com/dnlnln/generate-sql-merge/blob/c39e46edef6f21dedc7f6e375e6893d78308eb09/master.dbo.sp_generate_merge.sql) ✅.

reference: [history for master.dbo.sp_generate_merge.sql](https://github.com/dnlnln/generate-sql-merge/commits/master/master.dbo.sp_generate_merge.sql)

thanks for sharing/creating/maintaining a great tool! 🤝

**Comment by dnlnln** [comment] 2023-08-14 01:30
That's very peculiar, especially since it's showing `processing - instruction(x)` in your error, whereas [the actual identifier is `processing-instruction(x)`](https://github.com/dnlnln/generate-sql-merge/blob/16f28006ef42f5121b88763b5c342886e8b41fbf/master.dbo.sp_generate_merge.sql#L967C20-L967C20). I wonder if there's a file encoding issue. Which version of SQL are you using there?

**Comment by spottedmahn** [comment] 2023-08-14 16:13
>Which version of SQL are you using there?

<HTML>
<BODY>
<TABLE><TR><TD>Microsoft SQL Server 2022 (RTM-CU6) (KB5027505) - 16.0.4055.4 (X64) <br>	Jun 29 2023 15:43:13 <br>	Copyright (C) 2022 Microsoft Corporation<br>	Developer Edition (64-bit) on Linux (Ubuntu 20.04.6 LTS) &lt;X64&gt;</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by dnlnln** [comment] 2023-08-16 10:57
I just tried installing on `16.0.4065.3 (X64)` without issue, via VSCode and SSMS.

There's been a few more changes in the last week. Mind pulling master and seeing if the problem is still happening?

**Comment by dnlnln** [comment] 2023-08-28 02:05
Closing for now however please add a comment if the problem happens again

**Closed as completed by dnlnln** 2023-08-28 02:05 UTC
